### PR TITLE
@ #603 | make dir if not exists

### PR DESCRIPTION
**Pull request by datphan**
connect #603

### CODE REVIEW

**Review by phuonglm — CHANGES_REQUESTED** [review]
If `lookup_path` is exits and type is not directory what we will do?

**Comment by datphan** [comment]
@phuonglm what do you mean? do you have an example for that?

**Comment by phuonglm** [comment]
for example lookup_path is a file or symlink, do we delete that file and create directory or we warn user about that?

**Comment by datphan** [comment]
@phuonglm no, that is user problem, and I don't think it will happen with regular user anyway

**Comment by datphan** [comment]
@phuonglm but we still support it like you said, please check again.

**Review by phuonglm — APPROVED** [review]

**Review by hieptranquoc — APPROVED** [review]

**Review by hoatle — APPROVED** [review]
LGTM

**Pull request merged**
