### PR TITLE
@ #516 | update git clean check function

### PR DESCRIPTION
**Pull request by datphan**
connect #516

### CODE REVIEW

**Comment by hoatle** [comment]
@phuonglm please review this

**Comment by phuonglm** [comment]
seem we miss the case branch diverged. I think we should halt the sync if branch diverged.

```
phuonglm@:~/Projects/teracy/dev$ git status
On branch bug/git-clean-check
Your branch is up-to-date with 'datphan/develop'.
nothing to commit, working directory clean

phuonglm@:~/Projects/teracy/dev/extensions/teracy-dev-core$ git status
On branch develop
Your branch and 'origin/develop' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean

phuonglm@:~/Projects/teracy/dev$ vagrant status
Already on 'develop'
Current machine states:

iorad.local               poweroff (virtualbox)

The VM is powered off. To restart the VM, simply run `vagrant up`

phuonglm@:~/Projects/teracy/dev/extensions/teracy-dev-core$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```

**Comment by datphan** [comment]
@phuonglm other than develop/master branch, any other branch with clean working tree will treat as normal switching process, its mean if in the config we want the extension to be` branch-1`, it will swich to `branch-1` no matter what branch the repo were in (exclude master/develop with no clean working tree)

**Comment by datphan** [comment]
@phuonglm I've added diverged case, pls check again

**Review by phuonglm — APPROVED** [review]

**Pull request merged**
