### PR TITLE
@ #395 | dev-setup user flow best practices

### LINKED ISSUE #395: should add best practices docs for dev-setup user flow
consistency is the key, we defined the flow and we'll do the same for all to avoid confusion.

README and Upgrade flow:

```
<org>/<project> -> <org>/<project>/README -> <org>/dev-setup/README ->
<org>/<project>/dev-setup/README -> <org>/<project>/README
```

That's the flow for user onboarding (new setup or upgrading flow).

This will be applied through out all the dev-setup so that developers (users) from different projects can do the same, no more confusion, no more question asked, just follow the convention best practices.

### PR DESCRIPTION
**Pull request by hoatle**
connect #395

### CODE REVIEW

**Comment by hoatle** [comment]
@hoavt please help to review

**Review by hoavt — COMMENTED** [review]
@hoale Please check my pr.

**Comment by hoatle** [comment]
assigned to @phuonglm

**Comment by phuonglm** [comment]
```
[2017-11-13T11:03:40+03:00] ERROR: homebrew_package[git] (teracydev_installation::git line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["brew", "info", "--json=v1", "git"] ----
STDOUT: 
STDERR: Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:190: syntax error, unexpected $undefined, expecting keyword_end
      \thelper = osxkeychain
       ^
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:423:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:72:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:34:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
---- End output of ["brew", "info", "--json=v1", "git"] ----
Ran ["brew", "info", "--json=v1", "git"] returned 1
[2017-11-13T11:03:40+03:00] ERROR: homebrew_package[git] (teracydev_installation::git line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["brew", "info", "--json=v1", "git"] ----
STDOUT: 
STDERR: Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:190: syntax error, unexpected $undefined, expecting keyword_end
      \thelper = osxkeychain
       ^
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:423:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:72:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:34:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
---- End output of ["brew", "info", "--json=v1", "git"] ----
Ran ["brew", "info", "--json=v1", "git"] returned 1
[2017-11-13T11:03:40+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2017-11-13T11:03:40+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
-e:222:in `run': Chef-client failed (RuntimeError)
    from -e:242:in `<main>'
```
with MacOS serria on VM machine i got this error when run the automate script. Not sure the problem related to git version or not.

**Comment by hoatle** [comment]
@phuonglm please make sure to comment on the right issue.

**Review by phuonglm — APPROVED** [review]
the workflow ok for me.

**Pull request merged**
