### PR TITLE
@ #389 | vagrant reload --provision should not re-install the same installed packages

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #389

### CODE REVIEW

**Comment by hieptranquoc** [comment]
@hoale review this PR,plz

**Comment by hieptranquoc** [comment]
@hoale this include issue #387

**Comment by hoatle** [comment]
@phuonglm should help to review

**Review by phuonglm — APPROVED** [review]

**Review by hoatle — APPROVED** [review]
LGTM

**Pull request merged**
