### PR TITLE
@ #593 | add --tags when tag not found

### PR DESCRIPTION
**Pull request by datphan**
connect #593

### CODE REVIEW

**Comment by hoatle** [comment]
@datphan please send PR to the v0.6.0-x branch.

**Comment by hoatle** [comment]
and don't forget to follow our git branch name convention: http://dev.teracy.org/docs/workflow.html#workflow-in-teracy

**Comment by hoatle** [comment]
@datphan I cherry-picked the fix for the double quote bug, please rebase

**Comment by datphan** [comment]
I've moved to this PR https://github.com/teracyhq/dev/pull/595

**Pull request closed without merging**
