### PR TITLE
@ #195 | should check if vagrant 1.9 works the same as 1.8

### PR DESCRIPTION
**Pull request by hoatle**
connects #195 

teracy-dev works great with vagrant >=1.8.7 and >=1.9.1

### CODE REVIEW

**Comment by hoavt** [comment]
checked, vagrant 1.9.1 works well on Mac and Ubuntu. Do I need to check on Window? Don't see any changes in the doc for win.

**Comment by hoatle** [comment]
@hoavt docs updated for windows

**Comment by hoatle** [comment]
@hoavt I checked on Windows, it should work. Just review the docs is enough to merge this, you don't have to check on Windows now, just need to know which versions of vagrant should work.

**Comment by hoavt** [comment]
reviewed, it's ok to merge @hoatle

**Review by hoavt — APPROVED** [review]

**Pull request merged**
